# LogServer/docker-compose.yml
version: '3.8'

services:
  logserver:
    image: ghcr.io/louolm/easysave-logserver:latest
    ports:
      - "5000:5000"
    volumes:
      - ./central-logs:/app/central-logs
    restart: unless-stopped
    environment:
      - ASPNETCORE_URLS=http://+:5000