version: '3.8'

services:
  logserver:
    build:
      context: ..          # racine EasySave/
      dockerfile: LogServer/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./central-logs:/app/central-logs   # logs persistés sur l'hôte
    restart: unless-stopped