flowchart TD
  Start((' '))
  RT{Run type?}
  IM['Run in interactive mode']
  RA['Run with arguments']
  CL['Choose language FR/EN']
  CF['Choose file format JSON/XML']
  Menu{Menu}
  CreateJob['Create a job']
  DefName['Define name and directories']
  ChooseType['Choose job type full / differential']
  ViewJobs['View all jobs']
  RunJob['Run a job']
  RunArgs{Run with arguments?}
  SelectJobRun['Select job']
  FullBackup{Full backup?}
  CopyAll['Copy/Paste all between directories']
  CheckDiff['Check differentials between directories']
  CopyDiff['Copy/Paste differentials between directories']
  DeleteJob['Delete a job']
  SelectJobDel['Select job']
  Leave['Leave menu']
  End((' '))

  Start --> RT
  RT -->|interactive| IM
  RT -->|arguments| RA
  IM --> CL
  RA --> RunJob
  CL --> CF
  CF --> Menu


  Menu -->|create| CreateJob
  Menu -->|view| ViewJobs
  Menu -->|run| RunJob
  Menu -->|delete| DeleteJob
  Menu -->|leave| Leave

  CreateJob --> DefName --> ChooseType --> Menu
  ViewJobs --> Menu

  RunJob --> RunArgs
  RunArgs -->|yes| FullBackup
  RunArgs -->|no| SelectJobRun
  SelectJobRun --> FullBackup
  FullBackup -->|yes| CopyAll --> Menu
  FullBackup -->|no| CheckDiff --> CopyDiff --> Menu

  DeleteJob --> SelectJobDel --> Menu
  Leave --> End

  classDef processNode stroke:#818cf8,fill:#eef2ff,color:#1e1b4b
  classDef decisionNode stroke:#a78bfa,fill:#f5f3ff,color:#1e1b4b
  classDef actionNode stroke:#2dd4bf,fill:#f0fdfa,color:#1e1b4b
  classDef endNode stroke:#f87171,fill:#fef2f2,color:#1e1b4b

  class IM,RA,CL,FXML,FJSON,CreateJob,DefName,ChooseType,ViewJobs,RunJob,SelectJobRun,CopyAll,CheckDiff,CopyDiff,DeleteJob,SelectJobDel,Leave processNode
  class RT,CF,Menu,RunArgs,FullBackup decisionNode
  class Start,End endNode