flowchart TD
  Start((' '))
  RT{Run type?}
  IM['Run in graphic mode']
  RA['Run with arguments']
  Menu{Jobs}
  CreateJob['New job']
  DefName['Define name and directories']
  ChooseType['Choose job type full / differential']
  RunJob['Run a selected job']
  RunAllJob['Run all jobs']
  RunArgs{Run with arguments?}
  SelectJobRun['Select job']
  FullBackup{Full backup?}
  CopyAll['Copy/Paste all between directories']
  CheckDiff['Check differentials between directories']
  CopyDiff['Copy/Paste differentials between directories']
  DeleteJob['Delete a job']
  SelectJobDel['Select job']
  Leave['Leave menu']
  Settings['Open settings']
  SettingsMenu{Settings}
  Language['Choose language']
  BusinessSoftwareDetection['Choose the business software Dectection']
  CryptoSoftEncryption['CryptoSoft Encryption']
  Extensions['Choose the extensions to Encrypt']
  Key['Choose the Encryption Key']
  LogFileFormat['Choose the Log File Format JSON/XML']
  End((' '))

  Start --> RT
  RT -->|interactive| IM
  RT -->|arguments| RA
  IM --> Menu
  RA --> RunJob

  Menu -->|create| CreateJob
  Menu -->|run| RunJob
  Menu -->|runAll| RunAllJob
  Menu -->|delete| DeleteJob
  Menu -->|leave| Leave
  Menu -->|settings| Settings

  Settings --> SettingsMenu
  SettingsMenu --> Language
  SettingsMenu --> BusinessSoftwareDetection
  SettingsMenu --> CryptoSoftEncryption
  CryptoSoftEncryption --> Extensions
  CryptoSoftEncryption --> Key
  SettingsMenu --> LogFileFormat

  Language --> Menu
  BusinessSoftwareDetection --> Menu
  Extensions --> Menu
  Key --> Menu
  LogFileFormat--> Menu

  CreateJob --> DefName --> ChooseType --> Menu

  RunJob --> RunArgs
  RunArgs -->|yes| FullBackup
  RunArgs -->|no| SelectJobRun
  SelectJobRun --> FullBackup
  FullBackup -->|yes| CopyAll --> Menu
  FullBackup -->|no| CheckDiff --> CopyDiff --> Menu

  DeleteJob --> SelectJobDel --> Menu
  RunAllJob --> Menu
  Leave --> End

  classDef processNode stroke:#818cf8,fill:#eef2ff,color:#1e1b4b
  classDef decisionNode stroke:#a78bfa,fill:#f5f3ff,color:#1e1b4b
  classDef actionNode stroke:#2dd4bf,fill:#f0fdfa,color:#1e1b4b
  classDef endNode stroke:#f87171,fill:#fef2f2,color:#1e1b4b

  class IM,RA,CL,FXML,FJSON,CreateJob,DefName,ChooseType,ViewJobs,RunJob,SelectJobRun,CopyAll,CheckDiff,CopyDiff,DeleteJob,SelectJobDel,Leave processNode,
  class RT,CF,Menu,RunArgs,FullBackup decisionNode
  class Start,End endNode