%%{init: {"theme": "default"}}%%
graph LR

  User(["User"])

  subgraph EasySave["EasySave"]

    subgraph gestion["Job Management"]
      UC1(["Create a job"])
      UC2(["Edit a job"])
      UC3(["Delete a job"])
      UC30(["Open Logs"])
      UC31(["Pause a/all job(s)"])
      UC32(["Resume a/all job(s)"])
      UC33(["Stop a/all job(s)"])
      UC4(["Enter name/paths/type"])
      UC5(["Write in config.json"])
      UC55(["Open File Explorer"])
    end

    subgraph execution["Backup Execution"]
      UC6(["Run a job"])
      UC66(["Run selected job"])
      UC7(["Run all jobs"])
      UC8(["Copy files"])
      UC9(["Encrypt by CryptoSoft"])
      UC10(["Update state.json"])
      UC11(["Log (JSON/XML)"])
      UC12(["Block if software running"])
    end

    subgraph parametres["Settings"]
      UC13(["Set language"])
      UC14(["Set business software"])
      UC15(["Set priority file extensions"])
      UC16(["Set encryption"])
      UC17(["Set log format"])
      UC18(["Set log destination"])
      UC19(["Write in settings.json"])
    end

  end

  User --- UC1
  User --- UC2
  User --- UC3
  User --- UC30
  User --- UC31
  User --- UC32
  User --- UC33
  User --- UC66
  User --- UC7
  User --- UC13
  User --- UC14
  User --- UC15
  User --- UC16

  UC1 -. «include» .-> UC4
  UC1 -. «include» .-> UC5
  UC2 -. «include» .-> UC4
  UC2 -. «include» .-> UC5
  UC3 -. «include» .-> UC5
  UC30 -. «include» .-> UC55
  UC7 -. «include for each file» .-> UC6
  UC66 -. «include» .-> UC6
  UC6 -. «include» .-> UC8
  UC6 -. «include» .-> UC10
  UC6 -. «include» .-> UC11
  UC13 -. «include» .-> UC19
  UC14 -. «include» .-> UC19
  UC15 -. «include» .-> UC19
  UC16 -. «include» .-> UC19
  UC17 -. «include» .-> UC19
  UC18 -. «include» .-> UC19

  UC8 -. «extend» .-> UC9
  UC6 -. «extend» .-> UC12