using Avalonia.Controls;
using Avalonia.Platform.Storage;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using EasySave.Core;
using EasySave.Services;
using EasySave.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace EasySave.UI.ViewModels;

// ViewModel for the main job management screen.
// Manages the list of backup jobs, the create/edit form, per-job and global
// pause/resume/stop controls, and real-time progress display.
//
// [ObservableProperty] on a private field generates a public property that
// raises PropertyChanged on assignment, keeping the UI in sync automatically.
public partial class JobListViewModel : ViewModelBase
{
    private readonly IConfigRepository _configRepo;
    private IBackupService _backupService;
    private readonly ISettingsRepository _settingsRepo;
    private TranslationService _t;

    // Needed to open the native folder picker dialog (must have a parent window).
    public Window? ParentWindow { get; set; }

    [ObservableProperty] private ObservableCollection<BackupJob> _jobs = new();
    
    // Parallel collection of progress items, one per job, used to display
    // live status and percentage in the UI without mutating BackupJob directly.
    [ObservableProperty] private ObservableCollection<JobProgressItem> _jobProgress = new();
    [ObservableProperty] private BackupJob? _selectedJob;
    [ObservableProperty] private JobProgressItem? _selectedProgressItem;
    [ObservableProperty] private string _statusMessage = string.Empty;
    [ObservableProperty] private bool _statusIsError = false;
    [ObservableProperty] private bool _isFormVisible = false;

    // Translated UI labels bound to button and form controls.
    [ObservableProperty] private string _btnNewJob = string.Empty;
    [ObservableProperty] private string _btnRunSelected = string.Empty;
    [ObservableProperty] private string _btnRunAll = string.Empty;
    [ObservableProperty] private string _btnModify = string.Empty;
    [ObservableProperty] private string _btnDelete = string.Empty;
    [ObservableProperty] private string _btnPauseAll = string.Empty;
    [ObservableProperty] private string _btnResumeAll = string.Empty;
    [ObservableProperty] private string _btnStopAll = string.Empty;
    [ObservableProperty] private string _formTitle = string.Empty;
    [ObservableProperty] private string _lblName = string.Empty;
    [ObservableProperty] private string _lblSource = string.Empty;
    [ObservableProperty] private string _lblTarget = string.Empty;
    [ObservableProperty] private string _lblDiff = string.Empty;
    [ObservableProperty] private string _btnCancel = string.Empty;
    [ObservableProperty] private string _btnSave = string.Empty;
    [ObservableProperty] private string _btnBrowse = string.Empty;
    [ObservableProperty] private string _btnOpenLogs = string.Empty;

    // Form field values bound to the create/edit form inputs.
    [ObservableProperty] private string _formName = string.Empty;
    [ObservableProperty] private string _formSource = string.Empty;
    [ObservableProperty] private string _formTarget = string.Empty;
    [ObservableProperty] private bool _formIsDifferential = false;
    [ObservableProperty] private string _formNameError = string.Empty;
    [ObservableProperty] private string _formSourceError = string.Empty;
    [ObservableProperty] private string _formTargetError = string.Empty;

    // True when the form is in edit mode; false when creating a new job.
    private bool _isEditing = false;
    // One JobController per job, keyed by job ID, created on first run.
    private readonly Dictionary<int, JobController> _controllers = new();
    // Optional background watcher that pauses jobs when a business software is detected.
    private BusinessSoftwareWatcher? _watcher;

    public JobListViewModel(IConfigRepository configRepo, IBackupService backupService,
                            ISettingsRepository settingsRepo, TranslationService t)
    {
        _configRepo = configRepo;
        _backupService = backupService;
        _settingsRepo = settingsRepo;
        _t = t;
        UpdateTranslations(_t);
        Refresh();
    }

    // Keeps SelectedJob in sync when the user selects a row in the progress table.
    // The partial method is generated by [ObservableProperty] and called automatically
    // after SelectedProgressItem changes.
    partial void OnSelectedProgressItemChanged(JobProgressItem? value)
    {
        if (value == null) { SelectedJob = null; return; }
        SelectedJob = Jobs.FirstOrDefault(j => j.Id == value.JobId);
    }

    public void UpdateBackupService(IBackupService backupService)
        => _backupService = backupService;

    // Refreshes all translated strings. Called at startup and when the language changes.
    public void UpdateTranslations(TranslationService t)
    {
        _t = t;
        BtnNewJob = _t.T("jobs.new");
        BtnRunSelected = _t.T("jobs.runSelected");
        BtnRunAll = _t.T("jobs.runAll");
        BtnModify = _t.T("jobs.modify");
        BtnDelete = _t.T("jobs.delete");
        BtnPauseAll = _t.T("jobs.pauseAll");
        BtnResumeAll = _t.T("jobs.resumeAll");
        BtnStopAll = _t.T("jobs.stopAll");
        FormTitle = _t.T(_isEditing ? "form.title.edit" : "form.title.create");
        LblName = _t.T("form.name");
        LblSource = _t.T("form.source");
        LblTarget = _t.T("form.target");
        LblDiff = _t.T("form.diff");
        BtnCancel = _t.T("form.cancel");
        BtnSave = _t.T("form.save");
        BtnBrowse = _t.T("form.browse");
        BtnOpenLogs = _t.T("jobs.openLogs");
    }

    // Reloads jobs from disk and rebuilds the progress item collection to stay in sync.
    private void Refresh()
    {
        Jobs = new ObservableCollection<BackupJob>(_configRepo.Load());
        JobProgress = new ObservableCollection<JobProgressItem>(
        Jobs.Select(j => new JobProgressItem(
        j.Id,
        j.Name ?? "",
        j.Type.ToString(),
        j.SourcePath ?? "",
        j.TargetPath ?? ""
        )));
        StatusMessage = string.Empty;
        StatusIsError = false;
    }

    private JobProgressItem? GetProgress(int jobId)
        => JobProgress.FirstOrDefault(p => p.JobId == jobId);

    // Strips surrounding whitespace and quotes from a pasted path so users can
    // paste Explorer paths with or without surrounding quote characters.
    private static string CleanPath(string path) => path.Trim().Trim('"').Trim('\'').Trim();

    // ── Browse ────────────────────────────────────────────────────────────
    [RelayCommand]
    private async Task BrowseSource()
    {
        var path = await PickFolder();
        if (path != null) FormSource = path;
    }

    [RelayCommand]
    private async Task BrowseTarget()
    {
        var path = await PickFolder();
        if (path != null) FormTarget = path;
    }

    // Opens the native OS folder picker and returns the selected path, or null if the user cancelled.
    private async Task<string?> PickFolder()
    {
        if (ParentWindow == null) return null;
        var result = await ParentWindow.StorageProvider.OpenFolderPickerAsync(
            new FolderPickerOpenOptions { Title = _t.T("picker.title"), AllowMultiple = false });
        return result.Count > 0 ? result[0].Path.LocalPath : null;
    }

    // ── Formulaire ────────────────────────────────────────────────────────
    private bool ValidateForm()
    {
        var valid = true;

        if (string.IsNullOrWhiteSpace(FormName))
        { FormNameError = _t.T("err.nameRequired"); valid = false; }
        else FormNameError = string.Empty;

        var src = CleanPath(FormSource);
        if (string.IsNullOrWhiteSpace(src))
        { FormSourceError = _t.T("err.sourceRequired"); valid = false; }
        else if (!Directory.Exists(src))
        { FormSourceError = string.Format(_t.T("err.sourceNotFound"), src); valid = false; }
        else FormSourceError = string.Empty;

        var tgt = CleanPath(FormTarget);
        if (string.IsNullOrWhiteSpace(tgt))
        { FormTargetError = _t.T("err.targetRequired"); valid = false; }
        else FormTargetError = string.Empty;

        return valid;
    }

    [RelayCommand]
    private void ShowCreateForm()
    {
        _isEditing = false;
        FormName = FormSource = FormTarget = string.Empty;
        FormNameError = FormSourceError = FormTargetError = string.Empty;
        FormIsDifferential = false;
        FormTitle = _t.T("form.title.create");
        IsFormVisible = true;
    }

    [RelayCommand]
    private void ModifySelected()
    {
        if (SelectedJob == null) { SetError(_t.T("jobs.selectFirst")); return; }

        _isEditing = true;
        FormName = SelectedJob.Name ?? string.Empty;
        FormSource = SelectedJob.SourcePath ?? string.Empty;
        FormTarget = SelectedJob.TargetPath ?? string.Empty;
        FormIsDifferential = SelectedJob.Type == BackupType.Differential;
        FormNameError = FormSourceError = FormTargetError = string.Empty;
        FormTitle = _t.T("form.title.edit");
        IsFormVisible = true;
    }

    // Opens the edit form pre-filled with the job matching the given ID.
    // Used by per-row edit buttons in the job list.
    [RelayCommand]
    private void ModifyJob(int jobId)
    {
        var job = Jobs.FirstOrDefault(j => j.Id == jobId);
        if (job == null) return;

        SelectedJob = job;
        ModifySelected();
    }

    [RelayCommand]
    private void SaveJob()
    {
        if (!ValidateForm()) return;
        var src = CleanPath(FormSource);
        var tgt = CleanPath(FormTarget);
        var jobs = _configRepo.Load();
        bool wasEditing = _isEditing;

        if (!_isEditing && jobs.Any(j => j.Name!.Equals(FormName, StringComparison.OrdinalIgnoreCase)))
        { FormNameError = _t.T("err.nameExists"); return; }

        if (_isEditing && SelectedJob != null)
        {
            var ex = jobs.FirstOrDefault(j => j.Id == SelectedJob.Id);
            if (ex != null)
            {
                ex.Name = FormName; ex.SourcePath = src;
                ex.TargetPath = tgt;
                ex.Type = FormIsDifferential ? BackupType.Differential : BackupType.Full;
            }
        }
        else
        {
            // Assign an ID one higher than the current maximum to avoid reusing IDs
            // from deleted jobs.
            var id = jobs.Count == 0 ? 1 : jobs.Max(j => j.Id) + 1;
            jobs.Add(new BackupJob { Id = id, Name = FormName, SourcePath = src, TargetPath = tgt, Type = FormIsDifferential ? BackupType.Differential : BackupType.Full });
        }

        _configRepo.Save(jobs);
        IsFormVisible = false;
        _isEditing = false;
        SetSuccess(_t.T(wasEditing ? "jobs.updated" : "jobs.created"));
        Refresh();
    }

    [RelayCommand]
    private void CancelForm()
    {
        IsFormVisible = false;
        _isEditing = false;
        FormNameError = FormSourceError = FormTargetError = string.Empty;
    }

    // ── Run ───────────────────────────────────────────────────────────────
    [RelayCommand]
    private async Task RunSelected()
    {
        if (SelectedJob == null) { SetError(_t.T("jobs.selectFirst")); return; }
        var settings = _settingsRepo.Load();

        // Block the run immediately if the business software is already open.
        if (IsBusinessSoftwareActive(settings.BusinessSoftware))
        {
            SetError(string.Format(_t.T("jobs.blockedBusiness"), settings.BusinessSoftware));
            return;
        }
        // Start the watcher in case the software opens during the run.
        StartWatcher(settings);
        await StartJob(SelectedJob, settings);
        StopWatcher();
    }

    [RelayCommand]
    private async Task RunAll()
    {
        if (Jobs.Count == 0) { SetError(_t.T("jobs.noJobs")); return; }
        // Charge la config des paramètres
        var settings = _settingsRepo.Load();

        // Block the run immediately if the business software is already open.
        if (IsBusinessSoftwareActive(settings.BusinessSoftware))
        {
            SetError(string.Format(_t.T("jobs.blockedBusiness"), settings.BusinessSoftware));
            return;
        }
        // Start the watcher in case the software opens during the run.
        StartWatcher(settings);
        
        // Run all jobs concurrently and wait until every one has finished.
        var tasks = Jobs.Select(job => StartJob(job, settings)).ToList();
        await Task.WhenAll(tasks);
        StopWatcher();
        ShowSuccessAutoHide(string.Format(_t.T("jobs.allDone"), Jobs.Count));
    }
    // Returns true if a process with the given name is currently running.
    private static bool IsBusinessSoftwareActive(string processName)
    {
        //  if no process renseigné jsplus comment on traduit
        if (string.IsNullOrWhiteSpace(processName)) return false;
        // Nettoyage du nom
        var name = processName.Replace(".exe", "", StringComparison.OrdinalIgnoreCase).Trim();
        // True if 1+ service w/ this name is active
        return Process.GetProcessesByName(name).Length > 0;
    }

    private async Task StartJob(BackupJob job, AppSettings settings)
    {
        var prog = GetProgress(job.Id);
        if (prog == null) return;

        // Reuse an existing controller if available, or create a new one.
        // Reset() is called on reuse so the cancellation token is fresh.
        if (!_controllers.TryGetValue(job.Id, out var controller))
        {
            controller = new JobController();
            _controllers[job.Id] = controller;
        }
        else controller.Reset();

        prog.Status = "ACTIVE";
        prog.Percent = 0;
        prog.ProgressText = "0%";

        // Progress<double> marshals the callback onto the UI thread automatically,
        // but we still use Dispatcher.UIThread.Post to be explicit and avoid potential
        // cross-thread binding issues in Avalonia.
        var progress = new Progress<double>(pct =>
        {
            Avalonia.Threading.Dispatcher.UIThread.Post(() =>
            {
                prog.Percent = pct;
                prog.ProgressText = $"{pct:F0}%";
            });
        });

        // Run the backup on a thread-pool thread so the UI stays responsive.
        await Task.Run(() => _backupService.RunBackupAsync(job, settings, controller, progress));

        prog.Percent = controller.IsStopped ? prog.Percent : 100;
        prog.ProgressText = controller.IsStopped ? _t.T("jobs.stopped") : "100%";
        prog.Status = controller.IsStopped ? "STOPPED" : "DONE";

        if (!controller.IsStopped)
            ShowSuccessAutoHide(string.Format(_t.T("jobs.backupDone"), job.Name));

        // Reset the progress row to IDLE after a short delay so the user can see the final state before it disappears.
        _ = ResetProgressAfterDelay(prog);
    }

    // ── Watcher ───────────────────────────────────────────────────────────
    private void StartWatcher(AppSettings settings)
    {
        if (string.IsNullOrWhiteSpace(settings.BusinessSoftware)) return;
        _watcher = new BusinessSoftwareWatcher(
            settings.BusinessSoftware, _controllers.Values.ToList());
        _watcher.Start();
    }

    private void StopWatcher() { _watcher?.Stop(); _watcher = null; }

    // ── Per job Pause / Resume / Stop  ─────────────────────────────────────
    [RelayCommand]
    private void PauseJob(int jobId)
    {
        if (_controllers.TryGetValue(jobId, out var ctrl) && !ctrl.IsPaused)
        {
            ctrl.Pause();
            var p = GetProgress(jobId);
            if (p != null) p.Status = "PAUSED";
        }
    }

    [RelayCommand]
    private void ResumeJob(int jobId)
    {
        if (_controllers.TryGetValue(jobId, out var ctrl) && ctrl.IsPaused)
        {
            ctrl.Resume();
            var p = GetProgress(jobId);
            if (p != null) p.Status = "ACTIVE";
        }
    }

    [RelayCommand]
    private void StopJob(int jobId)
    {
        if (_controllers.TryGetValue(jobId, out var ctrl))
        {
            ctrl.Stop();
            var p = GetProgress(jobId);
            if (p != null) p.Status = "STOPPED";
        }
    }

    // ──Global  Pause / Resume / Stop  ─────────────────────────────────────
    [RelayCommand]
    private void PauseAll()
    {
        foreach (var (id, ctrl) in _controllers)
            if (!ctrl.IsPaused && !ctrl.IsStopped)
            {
                ctrl.Pause();
                var p = GetProgress(id);
                if (p != null) p.Status = "PAUSED";
            }
    }

    [RelayCommand]
    private void ResumeAll()
    {
        foreach (var (id, ctrl) in _controllers)
            if (ctrl.IsPaused)
            {
                ctrl.Resume();
                var p = GetProgress(id);
                if (p != null) p.Status = "ACTIVE";
            }
    }

    [RelayCommand]
    private void StopAll()
    {
        foreach (var (id, ctrl) in _controllers)
        {
            ctrl.Stop();
            var p = GetProgress(id);
            if (p != null) p.Status = "STOPPED";
        }
    }

    // ── Delete ────────────────────────────────────────────────────────────
    [RelayCommand]
    private async Task DeleteSelected()
    {
        if (SelectedJob == null) { SetError(_t.T("jobs.selectFirst")); return; }
        var jobs = _configRepo.Load();
        jobs.RemoveAll(j => j.Id == SelectedJob.Id);
        _configRepo.Save(jobs);
        ShowSuccessAutoHide(string.Format(_t.T("jobs.deleted"), SelectedJob.Name));
        Refresh();
    }

    [RelayCommand]
    private void OpenLogs()
    {
        var logsPath = Path.Combine(AppContext.BaseDirectory, "logs");
        Directory.CreateDirectory(logsPath);
        Process.Start(new ProcessStartInfo(logsPath) { UseShellExecute = true });
    }

    // ── Helpers ───────────────────────────────────────────────────────────
    private async Task SetSuccessAutoHide(string msg)
    {
        StatusIsError = false;
        StatusMessage = msg;
        await Task.Delay(5000);
        StatusMessage = string.Empty;
    }

    private void SetError(string msg) { StatusMessage = msg; StatusIsError = true; }
    private void SetSuccess(string msg) { StatusMessage = msg; StatusIsError = false; }
    // Clears the progress row back to IDLE 5 seconds after the job finishes
    // so the completed state is briefly visible without staying on screen forever.
    private async Task ResetProgressAfterDelay(JobProgressItem prog)
    {
        await Task.Delay(5000);

        Avalonia.Threading.Dispatcher.UIThread.Post(() =>
        {
            prog.Percent = 0;
            prog.ProgressText = "0%";
            prog.Status = "IDLE";
        });
    }

    // async void is intentional here: fire-and-forget auto-hide that does not
    // need to be awaited by the caller. Exceptions from Task.Delay are safe to ignore.
    private async void ShowSuccessAutoHide(string msg)
    {
        StatusIsError = false;
        StatusMessage = msg;

        await Task.Delay(5000);

        StatusMessage = string.Empty;
    }
}